namespace CPUSimulator.Core
{
    public enum ALUFunction : int
    {
        NoOperation,
        NegateZ,
        PassX,
        NegateX,
        PassY,
        NegateY,
        PassYFlipXY,
        PassXFlipXY,
        PassXSetYX,
        Increment,
        Decrement,
        Addition,
        Substraction,
        Multiplication,
        Division,
        Modulus,
        ShiftArithmeticallyLeft,
        ShiftArithmeticallyRight,
        Compare,
        And,
        Nand,
        Or,
        Nor,
        Xor,
        Nxor,
        ShiftLogicalLeft,
        ShiftLogicalRight,
        Comply,
        Min,
        Max
    }
}